# Velikost okna
WIDTH, HEIGHT = 800, 600

# Počet boidů
NUM_BOIDS = 400

# Nastavení boidů
BOID_SPEED = 2
BOID_RADIUS = 5
VISION_RADIUS = 50
SEPARATION_DISTANCE = 15

# Faktory chování (budou měněny UI)
COHESION_FACTOR = 0.01
ALIGNMENT_FACTOR = 0.05
SEPARATION_FACTOR = 0.1
